INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('개똥이의 여행1','즐거운 여행1');
INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('개똥이의 여행2','즐거운 여행2');
INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('개똥이의 여행3','즐거운 여행3');

INSERT INTO LPROD(LPROD_GU, LPROD_NM) VALUES('P101','컴퓨터제품');
INSERT INTO LPROD(LPROD_GU, LPROD_NM) VALUES('P102','전자제품');
INSERT INTO LPROD(LPROD_GU, LPROD_NM) VALUES('P103','여성 캐쥬얼 의류');